{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore\/VerintDelegate\/didStartSDKWithError:message:"},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore","doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore\/VerintDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expcore\/verintdelegate\/didstartsdkwitherror:message:"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartSDKWithError:message:"}],"modules":[{"name":"EXPCore"}],"navigatorTitle":[{"kind":"identifier","text":"didStartSDKWithError:message:"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)VerintDelegate(im)didStartSDKWithError:message:","roleHeading":"Instance Method","title":"didStartSDKWithError:message:"},"abstract":[{"text":"Tells the delegate that the SDK has been started, but a recoverable error occurred.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"didStartSDKWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EXPErrorCode","identifier":"doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore\/EXPErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPErrorCode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"text":"message:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error type"}]}],"name":"error"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A message describing the error"}]}],"name":"message"}],"kind":"parameters"}],"kind":"symbol","references":{"doc://com.Verint.EXPCore/documentation/EXPCore":{"title":"EXPCore","url":"\/documentation\/expcore","identifier":"doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://com.Verint.EXPCore/documentation/EXPCore/VerintDelegate":{"kind":"symbol","type":"topic","abstract":[{"text":"Delegates registered with the Verint SDK may adopt the ","type":"text"},{"code":"VerintDelegate","type":"codeVoice"},{"type":"text","text":" protocol to receive"},{"type":"text","text":" "},{"type":"text","text":"updates about the SDKâ€™s lifecycle."}],"role":"symbol","title":"VerintDelegate","fragments":[{"text":"VerintDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore\/VerintDelegate","url":"\/documentation\/expcore\/verintdelegate"},"doc://com.Verint.EXPCore/documentation/EXPCore/VerintDelegate/didStartSDKWithError:message:":{"abstract":[{"type":"text","text":"Tells the delegate that the SDK has been started, but a recoverable error occurred."}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"didStartSDKWithError:message:","kind":"identifier"}],"url":"\/documentation\/expcore\/verintdelegate\/didstartsdkwitherror:message:","role":"symbol","navigatorTitle":[{"text":"didStartSDKWithError:message:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore\/VerintDelegate\/didStartSDKWithError:message:","title":"didStartSDKWithError:message:"},"doc://com.Verint.EXPCore/documentation/EXPCore/EXPErrorCode":{"kind":"symbol","fragments":[{"text":"EXPErrorCode","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/expcore\/experrorcode","abstract":[{"type":"text","text":"Error code for Verint SDK"}],"identifier":"doc:\/\/com.Verint.EXPCore\/documentation\/EXPCore\/EXPErrorCode","title":"EXPErrorCode"}}}